version: "3.7"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FIREBASE_PROJECT_ID="onnorokompathsala"
      - FIREBASE_SERVICE_ACCOUNT_KEY_PATH=/app/serviceAccountKey.json
    volumes:
      - .:/app
    command: npm run start
